// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trustesse.Ivoluntia.Payment.Gateway.Data.Context;

#nullable disable

namespace Trustesse.Ivoluntia.Payment.Gateway.Migrations
{
    [DbContext(typeof(PaymentDataContext))]
    [Migration("20250822233504_MigrationPayment")]
    partial class MigrationPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Trustesse.Ivoluntia.Payment.Gateway.Models.PaymentRequestEntity", b =>
                {
                    b.Property<string>("PaymentRequestId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Initiatorid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceProviderReference")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PaymentRequestId");

                    b.ToTable("PaymentRequests");

                    b.HasData(
                        new
                        {
                            PaymentRequestId = "pay001",
                            Amount = "5000",
                            DateCreated = new DateTime(2025, 8, 22, 23, 35, 4, 327, DateTimeKind.Utc).AddTicks(5854),
                            DateUpdated = new DateTime(2025, 8, 22, 23, 35, 4, 327, DateTimeKind.Utc).AddTicks(5856),
                            Initiatorid = "user101",
                            ProgramId = "prog01",
                            ProgramType = "Scholarship",
                            ServiceProvider = "Paystack",
                            ServiceProviderReference = "psrefabc123",
                            Status = "initialize",
                            UserEmail = "testuser1@example.com"
                        },
                        new
                        {
                            PaymentRequestId = "pay002",
                            Amount = "7500",
                            DateCreated = new DateTime(2025, 8, 22, 23, 35, 4, 327, DateTimeKind.Utc).AddTicks(5859),
                            DateUpdated = new DateTime(2025, 8, 22, 23, 35, 4, 327, DateTimeKind.Utc).AddTicks(5860),
                            Initiatorid = "user102",
                            ProgramId = "prog02",
                            ProgramType = "Donation",
                            ServiceProvider = "Paystack",
                            ServiceProviderReference = "fwrefdef456",
                            Status = "initialize",
                            UserEmail = "testuser2@example.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
