// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trustesse.Ivoluntia.Payment.Gateway.Data.Context;

#nullable disable

namespace Trustesse.Ivoluntia.Payment.Gateway.Migrations
{
    [DbContext(typeof(PaymentDataContext))]
    partial class PaymentDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trustesse.Ivoluntia.Payment.Gateway.Models.PaymentRequestEntity", b =>
                {
                    b.Property<string>("PaymentRequestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Initiatorid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicePaidFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentRequestId");

                    b.ToTable("PaymentRequests");

                    b.HasData(
                        new
                        {
                            PaymentRequestId = "pay001",
                            Amount = 5000m,
                            DateCreated = new DateTime(2026, 2, 27, 17, 40, 4, 7, DateTimeKind.Utc).AddTicks(9626),
                            DateUpdated = new DateTime(2026, 2, 27, 17, 40, 4, 7, DateTimeKind.Utc).AddTicks(9626),
                            Initiatorid = "user101",
                            Reference = "psrefabc123",
                            ServiceId = "prog01",
                            ServicePaidFor = "Scholarship",
                            ServiceProvider = "paystack",
                            Status = "initialize",
                            UserEmail = "testuser1@example.com"
                        },
                        new
                        {
                            PaymentRequestId = "pay002",
                            Amount = 7500m,
                            DateCreated = new DateTime(2026, 2, 27, 17, 40, 4, 7, DateTimeKind.Utc).AddTicks(9630),
                            DateUpdated = new DateTime(2026, 2, 27, 17, 40, 4, 7, DateTimeKind.Utc).AddTicks(9631),
                            Initiatorid = "user102",
                            Reference = "fwrefdef456",
                            ServiceId = "prog02",
                            ServicePaidFor = "Donation",
                            ServiceProvider = "paystack",
                            Status = "initialize",
                            UserEmail = "testuser2@example.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
