# This workflow will build a .NET project
name: .NET

on:
  push:
    branches: [ "develop" , "main"]
  pull_request:
    branches: [ "develop" , "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Trustesse.Ivoluntia.Payment.Gateway.sln
      working-directory: Trustesse.Ivoluntia.Payment.Gateway

    - name: Build
      run: dotnet build Trustesse.Ivoluntia.Payment.Gateway.sln --no-restore
      working-directory: Trustesse.Ivoluntia.Payment.Gateway

    - name: Test
      run: dotnet test Trustesse.Ivoluntia.Payment.Gateway.sln --no-build --verbosity normal
      working-directory: Trustesse.Ivoluntia.Payment.Gateway
      
